name: workflow-services

on:
    push:
        branches:
            - main

jobs: 
  trabajo1: 
    runs-on: ubuntu-latest

    steps: 
      - name: listar archivos ahora
        run: ls -la
       